//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the BlueToque XsdCodeGenerator tool.
//     Tool Version:    2.19.418.0
//     Runtime Version: 4.0.30319.42000
//     Generated on:    2021-02-16 22:40:46
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. For more information see http://BlueToque.ca
// </autogenerated>
//------------------------------------------------------------------------------

//	http://BlueToque.ca
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace SharpGPX.GPX1_1.Topografix.GpxStyle {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    [System.Xml.Serialization.XmlRootAttribute("line", Namespace="http://www.topografix.com/GPX/gpx_style/0/2", IsNullable=false)]
    public partial class lineType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private byte[] colorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <summary />
        private decimal opacityField;
        
        /// <remarks/>
        public decimal opacity {
            get {
                return this.opacityField;
            }
            set {
                this.opacityField = value;
                this.RaisePropertyChanged("opacity");
            }
        }
        
        /// <summary />
        private bool opacityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opacitySpecified {
            get {
                return this.opacityFieldSpecified;
            }
            set {
                this.opacityFieldSpecified = value;
                this.RaisePropertyChanged("opacitySpecified");
            }
        }
        
        /// <summary />
        private decimal widthField;
        
        /// <remarks/>
        public decimal width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <summary />
        private bool widthFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("widthSpecified");
            }
        }
        
        /// <summary />
        private string patternField;
        
        /// <remarks/>
        public string pattern {
            get {
                return this.patternField;
            }
            set {
                this.patternField = value;
                this.RaisePropertyChanged("pattern");
            }
        }
        
        /// <summary />
        private linecapType linecapField;
        
        /// <remarks/>
        public linecapType linecap {
            get {
                return this.linecapField;
            }
            set {
                this.linecapField = value;
                this.RaisePropertyChanged("linecap");
            }
        }
        
        /// <summary />
        private bool linecapFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool linecapSpecified {
            get {
                return this.linecapFieldSpecified;
            }
            set {
                this.linecapFieldSpecified = value;
                this.RaisePropertyChanged("linecapSpecified");
            }
        }
        
        /// <summary />
        private dashTypeCollection dasharrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("dash", IsNullable=false)]
        public dashTypeCollection dasharray {
            get {
                return this.dasharrayField;
            }
            set {
                this.dasharrayField = value;
                this.RaisePropertyChanged("dasharray");
            }
        }
        
        /// <summary />
        private extensionsType extensionsField;
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
                this.RaisePropertyChanged("extensions");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    public enum linecapType {
        
        /// <remarks/>
        butt,
        
        /// <remarks/>
        round,
        
        /// <remarks/>
        square,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2", IsNullable=true)]
    public partial class dashType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private decimal markField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
                this.RaisePropertyChanged("mark");
            }
        }
        
        /// <summary />
        private decimal spaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal space {
            get {
                return this.spaceField;
            }
            set {
                this.spaceField = value;
                this.RaisePropertyChanged("space");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2", IsNullable=true)]
    public partial class extensionsType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    [System.Xml.Serialization.XmlRootAttribute("fill", Namespace="http://www.topografix.com/GPX/gpx_style/0/2", IsNullable=false)]
    public partial class fillType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private byte[] colorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <summary />
        private decimal opacityField;
        
        /// <remarks/>
        public decimal opacity {
            get {
                return this.opacityField;
            }
            set {
                this.opacityField = value;
                this.RaisePropertyChanged("opacity");
            }
        }
        
        /// <summary />
        private bool opacityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opacitySpecified {
            get {
                return this.opacityFieldSpecified;
            }
            set {
                this.opacityFieldSpecified = value;
                this.RaisePropertyChanged("opacitySpecified");
            }
        }
        
        /// <summary />
        private string patternField;
        
        /// <remarks/>
        public string pattern {
            get {
                return this.patternField;
            }
            set {
                this.patternField = value;
                this.RaisePropertyChanged("pattern");
            }
        }
        
        /// <summary />
        private extensionsType extensionsField;
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
                this.RaisePropertyChanged("extensions");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    [System.Xml.Serialization.XmlRootAttribute("text", Namespace="http://www.topografix.com/GPX/gpx_style/0/2", IsNullable=false)]
    public partial class textType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private byte[] colorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
        public byte[] color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <summary />
        private decimal opacityField;
        
        /// <remarks/>
        public decimal opacity {
            get {
                return this.opacityField;
            }
            set {
                this.opacityField = value;
                this.RaisePropertyChanged("opacity");
            }
        }
        
        /// <summary />
        private bool opacityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opacitySpecified {
            get {
                return this.opacityFieldSpecified;
            }
            set {
                this.opacityFieldSpecified = value;
                this.RaisePropertyChanged("opacitySpecified");
            }
        }
        
        /// <summary />
        private fontType fontField;
        
        /// <remarks/>
        public fontType font {
            get {
                return this.fontField;
            }
            set {
                this.fontField = value;
                this.RaisePropertyChanged("font");
            }
        }
        
        /// <summary />
        private alignType alignField;
        
        /// <remarks/>
        public alignType align {
            get {
                return this.alignField;
            }
            set {
                this.alignField = value;
                this.RaisePropertyChanged("align");
            }
        }
        
        /// <summary />
        private bool alignFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool alignSpecified {
            get {
                return this.alignFieldSpecified;
            }
            set {
                this.alignFieldSpecified = value;
                this.RaisePropertyChanged("alignSpecified");
            }
        }
        
        /// <summary />
        private verticalalignType verticalalignField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("vertical-align")]
        public verticalalignType verticalalign {
            get {
                return this.verticalalignField;
            }
            set {
                this.verticalalignField = value;
                this.RaisePropertyChanged("verticalalign");
            }
        }
        
        /// <summary />
        private bool verticalalignFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool verticalalignSpecified {
            get {
                return this.verticalalignFieldSpecified;
            }
            set {
                this.verticalalignFieldSpecified = value;
                this.RaisePropertyChanged("verticalalignSpecified");
            }
        }
        
        /// <summary />
        private extensionsType extensionsField;
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
                this.RaisePropertyChanged("extensions");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2", IsNullable=true)]
    public partial class fontType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private fontFamilyType familyField;
        
        /// <remarks/>
        public fontFamilyType family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
                this.RaisePropertyChanged("family");
            }
        }
        
        /// <summary />
        private decimal sizeField;
        
        /// <remarks/>
        public decimal size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        /// <summary />
        private bool sizeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
                this.RaisePropertyChanged("sizeSpecified");
            }
        }
        
        /// <summary />
        private weightType weightField;
        
        /// <remarks/>
        public weightType weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("weight");
            }
        }
        
        /// <summary />
        private bool weightFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
                this.RaisePropertyChanged("weightSpecified");
            }
        }
        
        /// <summary />
        private styleType styleField;
        
        /// <remarks/>
        public styleType style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
                this.RaisePropertyChanged("style");
            }
        }
        
        /// <summary />
        private bool styleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool styleSpecified {
            get {
                return this.styleFieldSpecified;
            }
            set {
                this.styleFieldSpecified = value;
                this.RaisePropertyChanged("styleSpecified");
            }
        }
        
        /// <summary />
        private textTransformType texttransformField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("text-transform")]
        public textTransformType texttransform {
            get {
                return this.texttransformField;
            }
            set {
                this.texttransformField = value;
                this.RaisePropertyChanged("texttransform");
            }
        }
        
        /// <summary />
        private bool texttransformFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool texttransformSpecified {
            get {
                return this.texttransformFieldSpecified;
            }
            set {
                this.texttransformFieldSpecified = value;
                this.RaisePropertyChanged("texttransformSpecified");
            }
        }
        
        /// <summary />
        private extensionsType extensionsField;
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
                this.RaisePropertyChanged("extensions");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2", IsNullable=true)]
    public partial class fontFamilyType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private string faceField;
        
        /// <remarks/>
        public string face {
            get {
                return this.faceField;
            }
            set {
                this.faceField = value;
                this.RaisePropertyChanged("face");
            }
        }
        
        /// <summary />
        private genericFontFamilyType genericField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public genericFontFamilyType generic {
            get {
                return this.genericField;
            }
            set {
                this.genericField = value;
                this.RaisePropertyChanged("generic");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    public enum genericFontFamilyType {
        
        /// <remarks/>
        serif,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sans-serif")]
        sansserif,
        
        /// <remarks/>
        cursive,
        
        /// <remarks/>
        fantasy,
        
        /// <remarks/>
        monospace,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    public enum weightType {
        
        /// <remarks/>
        normal,
        
        /// <remarks/>
        bold,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    public enum styleType {
        
        /// <remarks/>
        normal,
        
        /// <remarks/>
        italic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    public enum textTransformType {
        
        /// <remarks/>
        capitalize,
        
        /// <remarks/>
        uppercase,
        
        /// <remarks/>
        lowercase,
        
        /// <remarks/>
        none,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    [System.Xml.Serialization.XmlRootAttribute("align", Namespace="http://www.topografix.com/GPX/gpx_style/0/2", IsNullable=false)]
    public enum alignType {
        
        /// <remarks/>
        left,
        
        /// <remarks/>
        center,
        
        /// <remarks/>
        right,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="vertical-alignType", Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    [System.Xml.Serialization.XmlRootAttribute("vertical-align", Namespace="http://www.topografix.com/GPX/gpx_style/0/2", IsNullable=false)]
    public enum verticalalignType {
        
        /// <remarks/>
        top,
        
        /// <remarks/>
        center,
        
        /// <remarks/>
        bottom,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2", IsNullable=true)]
    public partial class dasharrayType : System.ComponentModel.INotifyPropertyChanged {
        
        /// <summary />
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <summary />
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        /// <summary />
        private dashTypeCollection dashField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dash")]
        public dashTypeCollection dash {
            get {
                return this.dashField;
            }
            set {
                this.dashField = value;
                this.RaisePropertyChanged("dash");
            }
        }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.topografix.com/GPX/gpx_style/0/2")]
    public partial class dashTypeCollection : System.Collections.Generic.List<dashType> {
    }
}
#pragma warning restore 1591