using SharpGPX;
using SharpGPX.GPX1_1;
using System;
using System.Linq;
using System.Security.Principal;

namespace Examples
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                if (args.Count() != 0)
                {
                    ReadAndPrint(args[0]);
                }
                else
                {
                    ReadAndPrint("Files\\All Buntzen Trails.gpx");
                    ReadAndPrint("Files\\Buntzen Waypoints.gpx");
                }

                // create a new file
                GpxClass newGpx = new GpxClass()
                {
                    Creator = WindowsIdentity.GetCurrent().Name,
                    Version = "Test",
                    Waypoints = new wptTypeCollection(),
                };

                wptType waypoint = new wptType()
                {
                    name = "Test Waypoint",
                    cmt = "Comment",
                    desc = "Description",
                    lat = (decimal)49.3402360,
                    lon = (decimal)-122.8770030,
                    time = DateTime.Now,
                    timeSpecified = true,
                    sym = "Waypoint",
                };

                newGpx.Waypoints.Add(waypoint);

                newGpx.ToFile("Test.gpx");

                CreateTrack();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error processing file:\r\n{0}", ex);
            }
        }

        private static void ReadAndPrint(string fileName)
        {
            Console.WriteLine("File Name: {0}", fileName);
            // read a file
            GpxClass gpx = GpxClass.FromFile(fileName);

            Console.WriteLine("Waypoints: {0}", gpx.Waypoints.Count);
            gpx.Waypoints.ForEach(x => Console.WriteLine("\tWaypoint: {0}", x.name));
            Console.WriteLine("Routes: {0}", gpx.Routes.Count);
            gpx.Routes.ForEach(x => Console.WriteLine("\tRoute: {0}, {1} points", x.name, x.rtept.Count));
            Console.WriteLine("Tracks: {0}", gpx.Tracks.Count);
            gpx.Tracks.ForEach(x => Console.WriteLine("\tTrack: {0}, {1} segments", x.name, x.trkseg.Count));
        }

        private static void CreateTrack()
        {
            GpxClass track = new GpxClass()
            {
                Metadata = new metadataType()
                {
                    author = new personType(WindowsIdentity.GetCurrent().Name, "Michael.Coyle@BlueToque.ca"),
                    link = new linkTypeCollection().AddLink(new linkType("www.BlueToque.ca", "Blue Toque Software")),
                    name = "Test Track",
                    desc = "Test track generated by SharpGPX",
                    copyright = new copyrightType("Blue Toque Software", "2020"),
                    
                },
            };

            track.Tracks.Add(new trkType()
            {
                name = "11-AUG-11 18:18:27",
                trkseg = new trksegTypeCollection().AddItem(
                    new trksegType()
                    {
                        trkpt = new wptTypeCollection()
                            .AddItem(new wptType(49.706482, -123.111961, 38.11))
                            .AddItem(new wptType(49.706417, -123.112190, 38.11))
                            .AddItem(new wptType(49.706348, -123.112495, 76.08))
                            .AddItem(new wptType(49.706242, -123.111961, 74.16))
                            .AddItem(new wptType(49.705872, -123.111961, 38.11))
                    })
            });

            track.Metadata.bounds = track.GetBounds();
            track.ToFile("Test2.gpx");
        }
    }
}